In [1]:
import pandas as pd
import numpy as np

# Load the Excel file
file_path = "I Sem BCA Dec 2024-Jan 2025 updated one new.xlsx"
df = pd.read_excel(file_path, sheet_name='Sheet2', header=None)

subject_code = input("Enter the subject code (e.g., BCACACS101): ").strip()
results = []
usn = None
name = None

# Iterate through the rows
for i in range(len(df)):
    row = df.iloc[i]

    # Update USN if found
    if str(row[4]).strip().upper() == 'USN':
        usn = row[5]

    # Check if subject code is in the row
    if subject_code in row.values:
        col_idx = list(row).index(subject_code)

        # Try to extract marks from next row
        try:
            mark_entry = df.iloc[i + 1, col_idx]
            if isinstance(mark_entry, str) and '+' in mark_entry:
                parts = mark_entry.replace('-', '0').split('+')
                parts = [float(p.strip()) for p in parts if p.strip().replace('.', '', 1).isdigit()]
                total_marks = sum(parts)
            else:
                total_marks = np.nan
        except:
            total_marks = np.nan

    # Once CGPA is reached, backtrack for name and finalize record
    if str(row[4]).strip().upper() == 'CGPA':
        for j in range(i - 1, max(i - 10, 0), -1):
            candidate_row = df.iloc[j]
            for col in range(4, 2, -1):
                val = candidate_row[col]
                if isinstance(val, str) and val.strip():
                    val = val.strip()
                    if not val.upper().startswith("USN") and val.upper() not in ["SGPA", "RESULT", "CLASS", "TERM GRADE", "M.C.NO"]:
                        name = val
                        break
            if name:
                break

        if name and usn and not pd.isna(total_marks):
            results.append((usn, name.upper(), total_marks))

            # Reset for next student
            name = None
            usn = None
            total_marks = None

# Create a DataFrame and sort by Total Marks descending
df_results = pd.DataFrame(results, columns=["USN", "Name", "Total Marks"])
df_results = df_results.dropna(subset=["Total Marks"])
df_results = df_results.sort_values(by="Total Marks", ascending=False)

# Save to Excel
output_file = input("Enter the name of the Excel file to save (without .xlsx): ")
df_results.to_excel(f"{output_file}.xlsx", index=False, engine='openpyxl')

print(f"✅ Saved to {output_file}.xlsx (sorted by Total Marks)")

Enter the subject code (e.g., BCACACS101):  BCACACS101
Enter the name of the Excel file to save (without .xlsx):  I SEM BCA BCACACS101

✅ Saved to I SEM BCA BCACACS101.xlsx (sorted by Total Marks)

In [3]:
df_results

Empty DataFrame
Columns: [USN, Name, Total Marks]
Index: []

In [10]:
import pandas as pd

# Load the Excel file
file_path = "F:\\Result Analysis\\I Sem BCA Dec 2024-Jan 2025 updated one new.xlsx"
df = pd.read_excel(file_path, sheet_name='Sheet2', header=None)

# Input
input_usn = input("Enter the USN (e.g., U05BB24S0001): ").strip().upper()
subject_code = input("Enter the Subject Code (e.g., BCACACS101): ").strip().upper()

found = False

# Iterate through the rows to find the subject code
for i in range(len(df)):
    row = df.iloc[i]

    if subject_code in row.values:
        col_idx = list(row).index(subject_code)

        # Try to get result from 10 rows below
        try:
            result_status = df.iloc[i + 10, col_idx]
        except:
            result_status = "Not found"

        # Locate USN and Name
        usn_row_index = None
        for j in range(i, min(i + 10, len(df))):
            if str(df.iloc[j, 4]).strip().upper() == 'USN':
                usn_row_index = j
                break

        if usn_row_index is not None:
            usn_row = df.iloc[usn_row_index]
            for c in range(len(usn_row)):
                if str(usn_row[c]).strip().upper() == input_usn:
                    # Column of the USN match
                    name = "Not found"
                    # Backtrack to find name before CGPA
                    for k in range(usn_row_index, usn_row_index + 20):
                        if k >= len(df): break
                        if str(df.iloc[k, 4]).strip().upper() == 'CGPA':
                            for m in range(k - 1, max(k - 10, 0), -1):
                                name_row = df.iloc[m]
                                for n in range(4, 2, -1):
                                    val = name_row[n]
                                    if isinstance(val, str) and val.strip():
                                        val = val.strip()
                                        if not val.upper().startswith("USN") and val.upper() not in ["SGPA", "RESULT", "CLASS", "TERM GRADE", "M.C.NO"]:
                                            name = val
                                            break
                                if name != "Not found":
                                    break
                            break

                    print(f"\n✅ Result Found:")
                    print(f"   Name         : {name}")
                    print(f"   USN          : {input_usn}")
                    print(f"   Subject Code : {subject_code}")
                    print(f"   Result       : {result_status}")
                    found = True
                    break
        if found:
            break

if not found:
    print(f"\n❌ Could not find PASS/FAIL status or student name for USN {input_usn} and subject {subject_code}.")

Enter the USN (e.g., U05BB24S0001):  U05BB24S0008
Enter the Subject Code (e.g., BCACACS101):  BCACACS103

✅ Result Found:
   Name         : Sumanth
   USN          : U05BB24S0008
   Subject Code : BCACACS103
   Result       : Pass

In [26]:
import pandas as pd

# Load the Excel file
file_path = "F:\\Result Analysis\\I Sem BCA Dec 2024-Jan 2025 updated one new.xlsx"

# Step 1: Read subject codes and names from Sheet1
df_subjects = pd.read_excel(file_path, sheet_name='Sheet1', header=None)
subjects = []

subjects = []

for i in range(len(df_subjects)):
    row = df_subjects.iloc[i]
    subject_code = str(row[3]).strip()
    subject_name = str(row[4]).strip()

    # Check if the code is 10 characters and alphanumeric (likely a subject code)
    if len(subject_code) == 10 and subject_code.isalnum():
        subjects.append((subject_code.upper(), subject_name))

In [27]:
subjects

[('BCACACS101', 'Fundamentals of Computers'),
 ('BCACACS102', 'Programming in C'),
 ('BCACACS103', 'Discrete Mathematics for Computer Applications'),
 ('BCACAPS104', 'Information Technology Lab'),
 ('BCACAPS105', 'C Programming Lab'),
 ('BCAENLS101', 'English Language'),
 ('BCAHDLS101', 'Hindi'),
 ('BCAKALS101', 'Kannada'),
 ('BCASKLS101', 'Sanskrit'),
 ('COMCOVS101', 'Constitutional Values')]

In [39]:
import pandas as pd

def get_result_for_usn_subject(df, input_usn, subject_code):
    input_usn = input_usn.strip().upper()
    subject_code = subject_code.strip().upper()

    for i in range(len(df)):
        row = df.iloc[i]

        if subject_code in row.values:
            col_idx = list(row).index(subject_code)

            # Try to get result from 10 rows below
            try:
                result_status = df.iloc[i + 10, col_idx]
            except:
                result_status = "Not found"

            # Locate USN row nearby (within next 10 rows)
            usn_row_index = None
            for j in range(i, min(i + 10, len(df))):
                if str(df.iloc[j, 4]).strip().upper() == 'USN':
                    usn_row_index = j
                    break

            if usn_row_index is not None:
                usn_row = df.iloc[usn_row_index]
                for c in range(len(usn_row)):
                    if str(usn_row[c]).strip().upper() == input_usn:
                        # Backtrack to find name before CGPA
                        name = "Not found"
                        for k in range(usn_row_index, min(usn_row_index + 20, len(df))):
                            if str(df.iloc[k, 4]).strip().upper() == 'CGPA':
                                for m in range(k - 1, max(k - 10, 0), -1):
                                    name_row = df.iloc[m]
                                    for n in range(4, 2, -1):
                                        val = name_row[n]
                                        if isinstance(val, str) and val.strip():
                                            val = val.strip()
                                            if not val.upper().startswith("USN") and val.upper() not in ["SGPA", "RESULT", "CLASS", "TERM GRADE", "M.C.NO"]:
                                                name = val
                                                break
                                    if name != "Not found":
                                        break
                                break

                        return {
                            "Name": name,
                            "USN": input_usn,
                            "Subject Code": subject_code,
                            "Result": result_status
                        }
    # If no match found after full scan:
    return {
        "Error": f"Could not find PASS/FAIL status or student name for USN {input_usn} and subject {subject_code}."
    }

# Usage example
if __name__ == "__main__":
    file_path = "F:\\Result Analysis\\I Sem BCA Dec 2024-Jan 2025 updated one new.xlsx"
    df = pd.read_excel(file_path, sheet_name='Sheet2', header=None)

    usn_input = input("Enter the USN (e.g., U05BB24S0001): ")
    subject_code_input = input("Enter the Subject Code (e.g., BCACACS101): ")

    result = get_result_for_usn_subject(df, usn_input, subject_code_input)

    if "Error" in result:
        print(f"\n❌ {result['Error']}")
    else:
        print(f"\n✅ Result Found:")
        print(f"   Name         : {result['Name']}")
        print(f"   USN          : {result['USN']}")
        print(f"   Subject Code : {result['Subject Code']}")
        print(f"   Result       : {result['Result']}")

Enter the USN (e.g., U05BB24S0001):  U05BB24S0008
Enter the Subject Code (e.g., BCACACS101):  BCACACS102

✅ Result Found:
   Name         : Sumanth
   USN          : U05BB24S0008
   Subject Code : BCACACS102
   Result       : Fail

In [42]:
def get_result_for_usn_subject(df, input_usn, subject_code):
    input_usn = input_usn.strip().upper()
    subject_code = subject_code.strip().upper()

    for i in range(len(df)):
        row = df.iloc[i]

        if subject_code in row.values:
            col_idx = list(row).index(subject_code)

            try:
                result_status = df.iloc[i + 10, col_idx]
            except:
                result_status = "Not Found"

            # Find USN row
            usn_row_index = None
            for j in range(i, min(i + 10, len(df))):
                if str(df.iloc[j, 4]).strip().upper() == 'USN':
                    usn_row_index = j
                    break

            if usn_row_index is not None:
                usn_row = df.iloc[usn_row_index]
                for c in range(len(usn_row)):
                    if str(usn_row[c]).strip().upper() == input_usn:
                        # Find name from CGPA region
                        name = "Not Found"
                        for k in range(usn_row_index, min(usn_row_index + 20, len(df))):
                            if str(df.iloc[k, 4]).strip().upper() == 'CGPA':
                                for m in range(k - 1, max(k - 10, 0), -1):
                                    name_row = df.iloc[m]
                                    for n in range(4, 2, -1):
                                        val = name_row[n]
                                        if isinstance(val, str) and val.strip():
                                            val = val.strip()
                                            if not val.upper().startswith("USN") and val.upper() not in ["SGPA", "RESULT", "CLASS", "TERM GRADE", "M.C.NO"]:
                                                name = val
                                                break
                                    if name != "Not Found":
                                        break
                                break

                        return {
                            "Name": name,
                            "USN": input_usn,
                            "Subject Code": subject_code,
                            "Result": result_status
                        }
    return {
        "Name": "Not Found",
        "USN": input_usn,
        "Subject Code": subject_code,
        "Result": "Not Found"
    }

# Main execution
if __name__ == "__main__":
    file_path = "F:\\Result Analysis\\I Sem BCA Dec 2024-Jan 2025 updated one new.xlsx"
    df = pd.read_excel(file_path, sheet_name='Sheet2', header=None)

    usn_input = input("Enter the USN (e.g., U05BB24S0001): ").strip().upper()
    print(f"\n📘 Results for USN: {usn_input}\n")

    results = []
    student_name = ""

    for code, name in subjects:
        res = get_result_for_usn_subject(df, usn_input, code)
        results.append((name, code, res["Result"]))
        if student_name == "":  # Capture name once
            student_name = res["Name"]

    print(f"Student Name: {student_name}\n")
    print("Subject-wise Results:")
    print("-" * 50)
    for subj_name, subj_code, result in results:
        print(f"{subj_name:<45} ({subj_code}): {result}")

Enter the USN (e.g., U05BB24S0001):  U05BB24S0018

📘 Results for USN: U05BB24S0018

Student Name: Pratha R Shetty

Subject-wise Results:
--------------------------------------------------
Fundamentals of Computers                     (BCACACS101): Pass
Programming in C                              (BCACACS102): Fail
Discrete Mathematics for Computer Applications (BCACACS103): Pass
Information Technology Lab                    (BCACAPS104): Pass
C Programming Lab                             (BCACAPS105): Pass
English Language                              (BCAENLS101): Pass
Hindi                                         (BCAHDLS101): Not Found
Kannada                                       (BCAKALS101): Pass
Sanskrit                                      (BCASKLS101): Not Found
Constitutional Values                         (COMCOVS101): Pass

In [44]:
def extract_usns_from_sheet(file_path, sheet_name='Sheet2'):
    df = pd.read_excel(file_path, sheet_name=sheet_name, header=None)
    usn_list = []

    for i in range(len(df)):
        row = df.iloc[i]
        if str(row[4]).strip().upper() == 'USN':
            for col in range(5, len(row)):
                val = row[col]
                if isinstance(val, str) and val.strip().upper().startswith('U'):
                    usn_list.append(val.strip().upper())

    return list(set(usn_list))  # Remove duplicates if any

In [45]:
file_path = "I Sem BCA Dec 2024-Jan 2025 updated one new.xlsx"
usns = extract_usns_from_sheet(file_path)

print("Extracted USNs:")
for usn in usns:
    print(usn)

Extracted USNs:
U05BB24S0036
U05BB24S0097
U05BB24S0088
U05BB24S0044
U05BB24S0093
U05BB24S0105
U05BB24S0070
U05BB24S0046
U05BB24S0051
U05BB24S0128
U05BB24S0019
U05BB24S0135
U05BB24S0047
U05BB24S0108
U05BB24S0062
U05BB24S0083
U05BB24S0063
U05BB24S0101
U05BB24S0137
U05BB24S0001
U05BB24S0059
U05BB24S0054
U05BB24S0113
U05BB24S0077
U05BB24S0094
U05BB24S0002
U05BB24S0022
U05BB24S0066
U05BB24S0138
U05BB24S0027
U05BB24S0085
U05BB24S0130
U05BB24S0121
U05BB24S0056
U05BB24S0074
U05BB24S0041
U05BB24S0058
U05BB24S0031
U05BB24S0071
U05BB24S0030
U05BB24S0045
U05BB24S0004
U05BB24S0102
U05BB24S0114
U05BB24S0082
U05BB24S0037
U05BB24S0033
U05BB24S0080
U05BB24S0076
U05BB24S0053
U05BB24S0078
U05BB24S0079
U05BB24S0042
U05BB24S0052
U05BB24S0098
U05BB24S0123
U05BB24S0025
U05BB24S0049
U05BB24S0009
U05BB24S0008
U05BB24S0084
U05BB24S0073
U05BB24S0091
U05BB24S0029
U05BB24S0038
U05BB24S0024
U05BB24S0020
U05BB24S0129
U05BB24S0010
U05BB24S0120
U05BB24S0034
U05BB24S0061
U05BB24S0111
U05BB24S0039
U05BB24S0133
U05BB24S0032
U05BB24S0017
U05BB24S0134
U05BB24S0016
U05BB24S0119
U05BB24S0116
U05BB24S0050
U05BB24S0055
U05BB24S0132
U05BB24S0110
U05BB24S0125
U05BB24S0043
U05BB24S0005
U05BB24S0092
U05BB24S0057
U05BB24S0136
U05BB24S0117
U05BB24S0021
U05BB24S0040
U05BB24S0064
U05BB24S0118
U05BB24S0028
U05BB24S0109
U05BB24S0026
U05BB24S0072
U05BB24S0124
U05BB24S0006
U05BB24S0126
U05BB24S0015
U05BB24S0081
U05BB24S0096
U05BB24S0089
U05BB24S0104
U05BB24S0018
U05BB24S0048
U05BB24S0086
U05BB24S0003
U05BB24S0068
U05BB24S0122
U05BB24S0127
U05BB24S0067
U05BB24S0107
U05BB24S0140
U05BB24S0115
U05BB24S0014
U05BB24S0087
U05BB24S0100
U05BB24S0106
U05BB24S0075
U05BB24S0007
U05BB24S0013
U05BB24S0099
U05BB24S0011
U05BB24S0069
U05BB24S0035
U05BB24S0095
U05BB24S0131
U05BB24S0060
U05BB24S0023
U05BB24S0012
U05BB24S0103

In [46]:
len(usns)

136

In [50]:
subjects_dict = {}
for i in subjects:
    code = i[0]
    name = i[1]
    subjects_dict[code]=name

In [52]:
subjects_dict

{'BCACACS101': 'Fundamentals of Computers',
 'BCACACS102': 'Programming in C',
 'BCACACS103': 'Discrete Mathematics for Computer Applications',
 'BCACAPS104': 'Information Technology Lab',
 'BCACAPS105': 'C Programming Lab',
 'BCAENLS101': 'English Language',
 'BCAHDLS101': 'Hindi',
 'BCAKALS101': 'Kannada',
 'BCASKLS101': 'Sanskrit',
 'COMCOVS101': 'Constitutional Values'}

In [79]:
file_path = "F:\\Result Analysis\\I Sem BCA Dec 2024-Jan 2025 updated one new.xlsx"
df = pd.read_excel(file_path, sheet_name='Sheet2', header=None)

def extract_subject_dict(file_path, sheet_name='Sheet1'):
    df_subjects = pd.read_excel(file_path, sheet_name=sheet_name, header=None)
    subjects_dict = {}

    for i in range(len(df_subjects)):
        row = df_subjects.iloc[i]
        subject_code = str(row[3]).strip()
        subject_name = str(row[4]).strip()

        # Check if the code is 10 characters and alphanumeric
        if len(subject_code) == 10 and subject_code.isalnum():
            subjects_dict[subject_code.upper()] = subject_name

    return subjects_dict

# Extract USNs
def extract_usns(df):
    usns = set()
    for i in range(len(df)):
        row = df.iloc[i]
        if str(row[4]).strip().upper() == 'USN':
            for col in range(5, len(row)):
                val = row[col]
                if isinstance(val, str) and val.strip().upper().startswith('U'):
                    usns.add(val.strip().upper())
    return sorted(usns)

# Result fetching logic
def get_result_for_usn_subject(df, input_usn, subject_code):
    input_usn = input_usn.strip().upper()
    subject_code = subject_code.strip().upper()

    for i in range(len(df)):
        row = df.iloc[i]
        if subject_code in row.values:
            col_idx = list(row).index(subject_code)
            try:
                result_status = df.iloc[i + 10, col_idx]
            except:
                result_status = ""

            usn_row_index = None
            for j in range(i, min(i + 10, len(df))):
                if str(df.iloc[j, 4]).strip().upper() == 'USN':
                    usn_row_index = j
                    break

            if usn_row_index is not None:
                usn_row = df.iloc[usn_row_index]
                for c in range(len(usn_row)):
                    if str(usn_row[c]).strip().upper() == input_usn:
                        name = "Not Found"
                        for k in range(usn_row_index, min(usn_row_index + 20, len(df))):
                            if str(df.iloc[k, 4]).strip().upper() == 'CGPA':
                                for m in range(k - 1, max(k - 10, 0), -1):
                                    name_row = df.iloc[m]
                                    for n in range(4, 2, -1):
                                        val = name_row[n]
                                        if isinstance(val, str) and val.strip():
                                            val = val.strip()
                                            if not val.upper().startswith("USN") and val.upper() not in ["SGPA", "RESULT", "CLASS", "TERM GRADE", "M.C.NO"]:
                                                name = val
                                                break
                                    if name != "Not Found":
                                        break
                                break
                        return {
                            "Name": name.upper(),
                            "USN": input_usn,
                            f"{subject_code} - {subjects_dict[subject_code]}": result_status
                        }
    return {
        "Name": "Not Found",
        "USN": input_usn,
        f"{subject_code} - {subjects_dict[subject_code]}": "N/A"
    }


def get_gpa_result_total_percent(df, input_usn):
    input_usn = input_usn.strip().upper()
    sgpa = "Not Found"
    cgpa = "Not Found"
    result_status = "Not Found"
    total_marks = "Not Found"
    max_total = "Not Found"
    percentage = "Not Found"

    for i in range(len(df)):
        row = df.iloc[i]

        # Look for USN match
        if str(row[4]).strip().upper() == 'USN':
            for col in range(5, len(row)):
                val = row[col]
                if isinstance(val, str) and val.strip().upper() == input_usn:
                    for j in range(i + 1, min(i + 40, len(df))):
                        label = str(df.iloc[j, 4]).strip().upper()
                        label2 = str(df.iloc[j, 6]).strip().upper()
                        print(f"Label : {label}")
                        if label == 'SGPA':
                            sgpa = df.iloc[j, 5]
                        elif label == 'CGPA':
                            cgpa = df.iloc[j, 5]
                        elif label.startswith("RESULT:"):
                            result_status = label.split(":")[-1].strip().upper()
                        if label2 == 'TOTAL':
                            total_marks = df.iloc[j, 16]  # Last column
                            print(f"Total Marks : {total_marks}")
                        elif label2 == 'MAX. TOTAL':
                            max_total = df.iloc[j, 16]
                            print(f"Max Total : {max_total}")

                        # Compute percentage if both totals are found
                        if isinstance(total_marks, (int, float)) and isinstance(max_total, (int, float)) and max_total != 0:
                            percentage = round((total_marks / max_total) * 100, 2)

                        # If all found, break early
                        if all(x != "Not Found" for x in [sgpa, cgpa, result_status, total_marks, max_total, percentage]):
                            return {
                                "USN": input_usn,
                                "SGPA": sgpa,
                                "CGPA": cgpa,
                                "Result": result_status,
                                "Total Marks": total_marks,
                                "Percentage": percentage
                            }
                    break

    return {
        "USN": input_usn,
        "SGPA": sgpa,
        "CGPA": cgpa,
        "Result": result_status,
        "Total Marks": total_marks,
        "Percentage": percentage
    }


# Build full dataset
usn_list = extract_usns(df)
subjects_dict = extract_subject_dict(file_path)
print(usn_list)
print(f"Total USNs : {len(usn_list)}")
full_data = []
sc = 0 
for usn in usn_list:
    student_row = {"USN": usn, "Name": "Not Found"}
    for code in subjects_dict:
        result = get_result_for_usn_subject(df, usn, code)
        student_row[f"{code} - {subjects_dict[code]}"] = result.get(f"{code} - {subjects_dict[code]}", "")
        if student_row["Name"] == "Not Found" and result["Name"] != "Not Found":
            student_row["Name"] = result["Name"]
    #print(student_row)
    sc+=1
    print(sc)
    if sc==10:
        break
    gpa_data = get_gpa_result_total_percent(df, usn)
    student_row["SGPA"] = gpa_data["SGPA"]
    student_row["CGPA"] = gpa_data["CGPA"]
    student_row["Result"] = gpa_data["Result"]
    student_row["Total Marks"] = gpa_data["Total Marks"]
    student_row["Percentage"] = gpa_data["Percentage"]
    full_data.append(student_row)

# Convert to DataFrame
final_df = pd.DataFrame(full_data)
# Insert Serial Number
final_df.insert(0, "Sl. No", range(1, len(final_df) + 1))

# Specify desired column order
subject_columns = [f"{code} - {subjects_dict[code]}" for code in subjects_dict]
final_columns = ["Sl. No", "Name", "USN"] + subject_columns + ["Result", "Total Marks", "Percentage", "CGPA", "SGPA"]

# Reorder DataFrame columns
final_df = final_df[final_columns]

# Save the result
output_file = "F:\\Result Analysis\\BCA_I_Sem_Subjectwise_Results.xlsx"
final_df.to_excel(output_file, index=False, engine='openpyxl')

print(f"✅ Final result saved to:\n{output_file}")

['U05BB24S0001', 'U05BB24S0002', 'U05BB24S0003', 'U05BB24S0004', 'U05BB24S0005', 'U05BB24S0006', 'U05BB24S0007', 'U05BB24S0008', 'U05BB24S0009', 'U05BB24S0010', 'U05BB24S0011', 'U05BB24S0012', 'U05BB24S0013', 'U05BB24S0014', 'U05BB24S0015', 'U05BB24S0016', 'U05BB24S0017', 'U05BB24S0018', 'U05BB24S0019', 'U05BB24S0020', 'U05BB24S0021', 'U05BB24S0022', 'U05BB24S0023', 'U05BB24S0024', 'U05BB24S0025', 'U05BB24S0026', 'U05BB24S0027', 'U05BB24S0028', 'U05BB24S0029', 'U05BB24S0030', 'U05BB24S0031', 'U05BB24S0032', 'U05BB24S0033', 'U05BB24S0034', 'U05BB24S0035', 'U05BB24S0036', 'U05BB24S0037', 'U05BB24S0038', 'U05BB24S0039', 'U05BB24S0040', 'U05BB24S0041', 'U05BB24S0042', 'U05BB24S0043', 'U05BB24S0044', 'U05BB24S0045', 'U05BB24S0046', 'U05BB24S0047', 'U05BB24S0048', 'U05BB24S0049', 'U05BB24S0050', 'U05BB24S0051', 'U05BB24S0052', 'U05BB24S0053', 'U05BB24S0054', 'U05BB24S0055', 'U05BB24S0056', 'U05BB24S0057', 'U05BB24S0058', 'U05BB24S0059', 'U05BB24S0060', 'U05BB24S0061', 'U05BB24S0062', 'U05BB24S0063', 'U05BB24S0064', 'U05BB24S0066', 'U05BB24S0067', 'U05BB24S0068', 'U05BB24S0069', 'U05BB24S0070', 'U05BB24S0071', 'U05BB24S0072', 'U05BB24S0073', 'U05BB24S0074', 'U05BB24S0075', 'U05BB24S0076', 'U05BB24S0077', 'U05BB24S0078', 'U05BB24S0079', 'U05BB24S0080', 'U05BB24S0081', 'U05BB24S0082', 'U05BB24S0083', 'U05BB24S0084', 'U05BB24S0085', 'U05BB24S0086', 'U05BB24S0087', 'U05BB24S0088', 'U05BB24S0089', 'U05BB24S0091', 'U05BB24S0092', 'U05BB24S0093', 'U05BB24S0094', 'U05BB24S0095', 'U05BB24S0096', 'U05BB24S0097', 'U05BB24S0098', 'U05BB24S0099', 'U05BB24S0100', 'U05BB24S0101', 'U05BB24S0102', 'U05BB24S0103', 'U05BB24S0104', 'U05BB24S0105', 'U05BB24S0106', 'U05BB24S0107', 'U05BB24S0108', 'U05BB24S0109', 'U05BB24S0110', 'U05BB24S0111', 'U05BB24S0113', 'U05BB24S0114', 'U05BB24S0115', 'U05BB24S0116', 'U05BB24S0117', 'U05BB24S0118', 'U05BB24S0119', 'U05BB24S0120', 'U05BB24S0121', 'U05BB24S0122', 'U05BB24S0123', 'U05BB24S0124', 'U05BB24S0125', 'U05BB24S0126', 'U05BB24S0127', 'U05BB24S0128', 'U05BB24S0129', 'U05BB24S0130', 'U05BB24S0131', 'U05BB24S0132', 'U05BB24S0133', 'U05BB24S0134', 'U05BB24S0135', 'U05BB24S0136', 'U05BB24S0137', 'U05BB24S0138', 'U05BB24S0140']
Total USNs : 136
1
Label : VENKATESH SOMAYYA NAIK
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: PASS
Total Marks : 503
Label : CLASS
Max Total : 650
2
Label : VISHWAS J
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: PASS
Total Marks : 538
Label : CLASS
Max Total : 650
3
Label : SANJANA SHETTY
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: PASS
Total Marks : 453
Label : CLASS
Max Total : 650
4
Label : DEEPTHI
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: PASS
Total Marks : 512
Label : CLASS
Max Total : 650
5
Label : VIJETHA
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: PASS
Total Marks : 435
Label : CLASS
Max Total : 650
6
Label : KHUSHI
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: PASS
Total Marks : 558
Label : CLASS
Max Total : 650
7
Label : PRAJWAL
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: PASS
Total Marks : 517
Label : CLASS
Max Total : 650
8
Label : SUMANTH
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: FAIL
Total Marks : 293
Label : CLASS
Max Total : 650
9
Label : AKSHAYA
Label : NAN
Label : NAN
Label : SGPA
Label : CGPA
Label : RESULT: PASS
Total Marks : 512
Label : CLASS
Max Total : 650
10
✅ Final result saved to:
F:\Result Analysis\BCA_I_Sem_Subjectwise_Results.xlsx

In [80]:
## Final Script Debug

In [93]:
import pandas as pd
from io import BytesIO
from IPython.display import display

# === USER INPUT ===
excel_path = "F:\\Result Analysis\\III Sem B.Com Dec Jan 2025 new.xlsx"  # Replace with actual file path
output_filename = "Semester_Result_Analysis"  # Output file name without extension

# === FUNCTIONS ===

def extract_subject_dict(file) -> dict:
    df_subjects = pd.read_excel(file, sheet_name='Sheet1', header=None)
    subjects_dict = {}
    for i in range(len(df_subjects)):
        row = df_subjects.iloc[i]
        subject_code = str(row[3]).strip()
        subject_name = str(row[4]).strip()
        if len(subject_code) == 10 and subject_code.isalnum():
            subjects_dict[subject_code.upper()] = subject_name
    return subjects_dict

def extract_usns(df):
    student_blocks = []
    for i in range(len(df)):
        if str(df.iloc[i, 4]).strip().upper() == 'USN':
            for col in range(5, len(df.columns)):
                val = df.iloc[i, col]
                if isinstance(val, str) and val.strip().upper().startswith('U'):
                    student_blocks.append((val.strip().upper(), i))  # (USN, start_row)
                    break
    return student_blocks

def get_result_for_usn_subject(block, input_usn, subject_code, subjects_dict):
    subject_code = subject_code.strip().upper()
    for i in range(len(block)):
        row = block.iloc[i]
        if subject_code in row.values:
            col_idx = list(row).index(subject_code)
            try:
                result_status = block.iloc[i + 10, col_idx]
            except:
                result_status = ""

            name = "Not Found"

            for i in range(len(block) - 1):
                if str(block.iloc[i, 4]).strip().upper() == 'USN':
                    val = str(block.iloc[i + 1, 4]).strip()
                    if val and not val.upper().startswith("U0") and len(val.split()) >= 1:
                        name = val
                    break

            return {
                "Name": name.upper(),
                "USN": input_usn,
                f"{subject_code} - {subjects_dict[subject_code]}": result_status
            }

    return {
        "Name": "Not Found",
        "USN": input_usn,
        f"{subject_code} - {subjects_dict[subject_code]}": "N/A"
    }

def get_gpa_result_total_percent(block, input_usn):
    sgpa = cgpa = result_status = total_marks = max_total = percentage = "Not Found"

    for i in range(len(block)):
        row = block.iloc[i]
        label = str(row[4]).strip().upper()
        label2 = str(row[6]).strip().upper()
        if label == 'SGPA':
            sgpa = row[5]
        elif label == 'CGPA':
            cgpa = row[5]
        elif label.startswith("RESULT:"):
            result_status = label.split(":")[-1].strip().upper()

    return {
        "USN": input_usn,
        "SGPA": sgpa,
        "CGPA": cgpa,
        "Result": result_status,
    }

def get_total_and_percentage(block):
    total_marks = max_total = percentage = None

    for i in range(len(block)):
        row = block.iloc[i]
        if "Total" in row.values:
            try:
                col_idx = list(row).index("Total")
                total_marks = block.iloc[i + 7, col_idx]
                max_total = block.iloc[i + 8, col_idx]

                if isinstance(total_marks, (int, float)) and isinstance(max_total, (int, float)) and max_total != 0:
                    percentage = round((total_marks / max_total) * 100, 2)
            except Exception as e:
                print(f"Error extracting totals: {e}")
            break

    return {
        "Total Marks": total_marks,
        "Max Marks": max_total,
        "Percentage": percentage
    }

def clean_to_int(val):
    if isinstance(val, float) and val.is_integer():
        return int(val)
    return val
# === MAIN PROCESSING ===

df = pd.read_excel(excel_path, sheet_name='Sheet2', header=None)
subjects_dict = extract_subject_dict(excel_path)
student_blocks = extract_usns(df)

print(student_blocks)
full_data = []

for idx, (usn, start_idx) in enumerate(student_blocks, start=1):
    block = df.iloc[start_idx-5:start_idx + 12]
    student_row = {"USN": usn, "Name": "Not Found"}

    for code in subjects_dict:
        result = get_result_for_usn_subject(block, usn, code, subjects_dict)
        student_row[f"{code} - {subjects_dict[code]}"] = result.get(f"{code} - {subjects_dict[code]}", "")
        if student_row["Name"] == "Not Found" and result["Name"] != "Not Found":
            student_row["Name"] = result["Name"]

    gpa_data = get_gpa_result_total_percent(block, usn)
    student_row["SGPA"] = gpa_data["SGPA"]
    student_row["CGPA"] = gpa_data["CGPA"]
    student_row["Result"] = gpa_data["Result"]

    # 🔁 Add Total & Percentage
    total_data = get_total_and_percentage(block)
    student_row["Total Marks"] = clean_to_int(total_data["Total Marks"])
    student_row["Max Marks"] = clean_to_int(total_data["Max Marks"])
    student_row["Percentage"] = total_data["Percentage"]

    full_data.append(student_row)


final_df = pd.DataFrame(full_data)
final_df.insert(0, "Sl. No", range(1, len(final_df) + 1))
subject_columns = [f"{code} - {subjects_dict[code]}" for code in subjects_dict]
final_columns = ["Sl. No", "Name", "USN"] + subject_columns + ["Result", "Total Marks", "Max Marks", "Percentage", "CGPA", "SGPA"]
final_df = final_df[final_columns]
# Convert and clean 'Total Marks' and 'Max Marks' — replace NaNs or invalid with 0 and make integers
final_df["Total Marks"] = pd.to_numeric(final_df["Total Marks"], errors="coerce").fillna(0).astype(int)
final_df["Max Marks"] = pd.to_numeric(final_df["Max Marks"], errors="coerce").fillna(0).astype(int)

# Optional: Round percentage to 2 decimals (only if it's numeric)
final_df["Percentage"] = final_df["Percentage"].apply(lambda x: round(x, 2) if isinstance(x, (float, int)) else 0.0)


# === DISPLAY & EXPORT ===
display(final_df)

[('U05BB21C0040', 10), ('U05BB21C0050', 25), ('U05BB21C0100', 40), ('U05BB21C0116', 55), ('U05BB21C0198', 69), ('U05BB21C0238', 84), ('U05BB21C0246', 99), ('U05BB21C0275', 114), ('U05SK22C0178', 129), ('U05BB22C0020', 144), ('U05GU22C0019', 159), ('U05BB22C0075', 174), ('U05BB22C0080', 189), ('U05BB22C0161', 203), ('U05BB22C0175', 218), ('U05BB22C0178', 233), ('U05BB22C0181', 248), ('U05BB22C0182', 263), ('U05BB22C0184', 278), ('U05BB22C0190', 293), ('U05BB22C0226', 308), ('U05BB22C0234', 323), ('U05BB22C0243', 337), ('U05BB22C0244', 352), ('U05BB22C0274', 367), ('U05BB22C0280', 382), ('U05BB22C0283', 397), ('U05BB22C0299', 412), ('U05BB22C0311', 427), ('U05BB22C0313', 442), ('U05BB22C0321', 456), ('U05BB22C0322', 471), ('U05BB22C0328', 486), ('U05BB22C0332', 501), ('U05BB22C0333', 516), ('U05BB22C0338', 531), ('U05BB22C0339', 546), ('U05BA23C0017', 561), ('U05TU23C0124', 576), ('U05BB23C0001', 590), ('U05BB23C0002', 605), ('U05BB23C0003', 620), ('U05BB23C0004', 635), ('U05BB23C0005', 650), ('U05BB23C0006', 665), ('U05BB23C0007', 680), ('U05BB23C0008', 695), ('U05BB23C0009', 710), ('U05BB23C0010', 724), ('U05BB23C0011', 739), ('U05BB23C0012', 754), ('U05BB23C0013', 769), ('U05BB23C0014', 784), ('U05BB23C0015', 799), ('U05BB23C0016', 814), ('U05BB23C0017', 829), ('U05BB23C0018', 844), ('U05BB23C0019', 858), ('U05BB23C0020', 873), ('U05BB23C0021', 888), ('U05BB23C0022', 903), ('U05BB23C0023', 918), ('U05BB23C0024', 933), ('U05BB23C0025', 948), ('U05BB23C0026', 963), ('U05BB23C0027', 978), ('U05BB23C0028', 992), ('U05BB23C0029', 1007), ('U05BB23C0030', 1022), ('U05BB23C0031', 1037), ('U05BB23C0032', 1052), ('U05BB23C0033', 1067), ('U05BB23C0034', 1082), ('U05BB23C0035', 1097), ('U05BB23C0036', 1112), ('U05BB23C0037', 1126), ('U05BB23C0038', 1141), ('U05BB23C0039', 1156), ('U05BB23C0040', 1171), ('U05BB23C0041', 1186), ('U05BB23C0042', 1201), ('U05BB23C0044', 1216), ('U05BB23C0045', 1231), ('U05BB23C0046', 1246), ('U05BB23C0047', 1260), ('U05BB23C0048', 1275), ('U05BB23C0049', 1290), ('U05BB23C0050', 1305), ('U05BB23C0051', 1320), ('U05BB23C0052', 1335), ('U05BB23C0053', 1350), ('U05BB23C0054', 1365), ('U05BB23C0055', 1380), ('U05BB23C0056', 1394), ('U05BB23C0057', 1409), ('U05BB23C0058', 1424), ('U05BB23C0059', 1439), ('U05BB23C0061', 1454), ('U05BB23C0062', 1469), ('U05BB23C0063', 1484), ('U05BB23C0064', 1499), ('U05BB23C0065', 1514), ('U05BB23C0066', 1528), ('U05BB23C0067', 1543), ('U05BB23C0068', 1558), ('U05BB23C0070', 1573), ('U05BB23C0071', 1588), ('U05BB23C0072', 1603), ('U05BB23C0073', 1618), ('U05BB23C0074', 1633), ('U05BB23C0075', 1648), ('U05BB23C0076', 1662), ('U05BB23C0077', 1677), ('U05BB23C0078', 1692), ('U05BB23C0079', 1707), ('U05BB23C0080', 1722), ('U05BB23C0081', 1737), ('U05BB23C0082', 1752), ('U05BB23C0083', 1767), ('U05BB23C0084', 1782), ('U05BB23C0085', 1796), ('U05BB23C0086', 1811), ('U05BB23C0087', 1826), ('U05BB23C0088', 1841), ('U05BB23C0089', 1856), ('U05BB23C0090', 1871), ('U05BB23C0091', 1886), ('U05BB23C0092', 1901), ('U05BB23C0093', 1916), ('U05BB23C0094', 1930), ('U05BB23C0095', 1945), ('U05BB23C0096', 1960), ('U05BB23C0097', 1975), ('U05BB23C0098', 1990), ('U05BB23C0099', 2005), ('U05BB23C0100', 2020), ('U05BB23C0101', 2035), ('U05BB23C0102', 2050), ('U05BB23C0103', 2064), ('U05BB23C0105', 2079), ('U05BB23C0106', 2094), ('U05BB23C0107', 2109), ('U05BB23C0108', 2124), ('U05BB23C0109', 2139), ('U05BB23C0110', 2154), ('U05BB23C0111', 2169), ('U05BB23C0112', 2184), ('U05BB23C0113', 2198), ('U05BB23C0114', 2213), ('U05BB23C0115', 2228), ('U05BB23C0116', 2243), ('U05BB23C0117', 2258), ('U05BB23C0118', 2273), ('U05BB23C0119', 2288), ('U05BB23C0120', 2303), ('U05BB23C0121', 2318), ('U05BB23C0122', 2332), ('U05BB23C0123', 2347), ('U05BB23C0124', 2362), ('U05BB23C0125', 2377), ('U05BB23C0126', 2392), ('U05BB23C0127', 2407), ('U05BB23C0128', 2422), ('U05BB23C0129', 2437), ('U05BB23C0130', 2452), ('U05BB23C0131', 2466), ('U05BB23C0132', 2481), ('U05BB23C0133', 2496), ('U05BB23C0134', 2511), ('U05BB23C0135', 2526), ('U05BB23C0136', 2541), ('U05BB23C0137', 2556), ('U05BB23C0138', 2571), ('U05BB23C0139', 2586), ('U05BB23C0140', 2600), ('U05BB23C0141', 2615), ('U05BB23C0142', 2630), ('U05BB23C0143', 2645), ('U05BB23C0144', 2660), ('U05BB23C0145', 2675), ('U05BB23C0146', 2690), ('U05BB23C0147', 2705), ('U05BB23C0148', 2720), ('U05BB23C0149', 2734), ('U05BB23C0150', 2749), ('U05BB23C0151', 2764), ('U05BB23C0152', 2779), ('U05BB23C0153', 2794), ('U05BB23C0154', 2809), ('U05BB23C0155', 2824), ('U05BB23C0156', 2839), ('U05BB23C0157', 2854), ('U05BB23C0158', 2868), ('U05BB23C0159', 2883), ('U05BB23C0160', 2898), ('U05BB23C0161', 2913), ('U05BB23C0162', 2928), ('U05BB23C0163', 2943), ('U05BB23C0164', 2958), ('U05BB23C0165', 2973), ('U05BB23C0167', 2988), ('U05BB23C0168', 3002), ('U05BB23C0169', 3017), ('U05BB23C0170', 3032), ('U05BB23C0171', 3047), ('U05BB23C0172', 3062), ('U05BB23C0173', 3077), ('U05BB23C0174', 3092), ('U05BB23C0175', 3107), ('U05BB23C0176', 3122), ('U05BB23C0177', 3136), ('U05BB23C0178', 3151), ('U05BB23C0179', 3166), ('U05BB23C0180', 3181), ('U05BB23C0181', 3196), ('U05BB23C0183', 3211), ('U05BB23C0184', 3226), ('U05BB23C0185', 3241), ('U05BB23C0186', 3256), ('U05BB23C0187', 3270), ('U05BB23C0188', 3285), ('U05BB23C0189', 3300), ('U05BB23C0190', 3315), ('U05BB23C0191', 3330), ('U05BB23C0192', 3345), ('U05BB23C0193', 3360), ('U05BB23C0194', 3375), ('U05BB23C0195', 3390), ('U05BB23C0196', 3404), ('U05BB23C0197', 3419), ('U05BB23C0198', 3434), ('U05BB23C0199', 3449), ('U05BB23C0200', 3464), ('U05BB23C0201', 3479), ('U05BB23C0202', 3494), ('U05BB23C0203', 3509), ('U05BB23C0204', 3524), ('U05BB23C0205', 3538), ('U05BB23C0206', 3553), ('U05BB23C0207', 3568), ('U05BB23C0208', 3583), ('U05BB23C0209', 3598), ('U05BB23C0210', 3613), ('U05BB23C0211', 3628), ('U05BB23C0212', 3643), ('U05BB23C0213', 3657), ('U05BB23C0214', 3672), ('U05BB23C0215', 3687), ('U05BB23C0216', 3702), ('U05BB23C0217', 3717), ('U05BB23C0218', 3732), ('U05BB23C0219', 3747), ('U05BB23C0220', 3762), ('U05BB23C0221', 3777), ('U05BB23C0222', 3791), ('U05BB23C0223', 3806), ('U05BB23C0224', 3821), ('U05BB23C0225', 3836), ('U05BB23C0226', 3851), ('U05BB23C0227', 3866), ('U05BB23C0228', 3881), ('U05BB23C0229', 3896), ('U05BB23C0230', 3911), ('U05BB23C0231', 3925), ('U05BB23C0232', 3940), ('U05BB23C0233', 3955), ('U05BB23C0234', 3970), ('U05BB23C0235', 3985), ('U05BB23C0236', 4000), ('U05BB23C0237', 4015), ('U05BB23C0238', 4030), ('U05BB23C0239', 4045), ('U05BB23C0240', 4059), ('U05BB23C0241', 4074), ('U05BB23C0242', 4089), ('U05BB23C0243', 4104), ('U05BB23C0244', 4119), ('U05BB23C0245', 4134), ('U05BB23C0246', 4149), ('U05BB23C0247', 4164), ('U05BB23C0248', 4179), ('U05BB23C0249', 4193), ('U05BB23C0250', 4208), ('U05BB23C0251', 4223), ('U05BB23C0252', 4238), ('U05BB23C0253', 4253), ('U05BB23C0254', 4268), ('U05BB23C0255', 4283), ('U05BB23C0256', 4298), ('U05BB23C0257', 4313), ('U05BB23C0258', 4327), ('U05BB23C0259', 4342), ('U05BB23C0260', 4357), ('U05BB23C0261', 4372), ('U05BB23C0262', 4387), ('U05BB23C0264', 4402), ('U05BB23C0265', 4417), ('U05BB23C0266', 4432), ('U05BB23C0267', 4447), ('U05BB23C0268', 4461), ('U05BB23C0269', 4476), ('U05BB23C0270', 4491), ('U05BB23C0271', 4506), ('U05BB23C0272', 4521), ('U05BB23C0273', 4536), ('U05BB23C0274', 4551), ('U05BB23C0275', 4566), ('U05BB23C0276', 4581), ('U05BB23C0277', 4595), ('U05BB23C0278', 4610), ('U05BB23C0279', 4625), ('U05BB23C0281', 4640), ('U05BB23C0282', 4655), ('U05BB23C0283', 4670), ('U05BB23C0284', 4685), ('U05BB23C0285', 4700), ('U05BB23C0286', 4715), ('U05BB23C0287', 4729), ('U05BB23C0288', 4744), ('U05BB23C0289', 4759), ('U05BB23C0290', 4774), ('U05BB23C0291', 4789), ('U05BB23C0292', 4804), ('U05BB23C0293', 4819), ('U05BB23C0294', 4834), ('U05BB23C0295', 4849), ('U05BB23C0296', 4863), ('U05BB23C0297', 4878), ('U05BB23C0298', 4893), ('U05BB23C0299', 4908), ('U05BB23C0300', 4923), ('U05BB23C0301', 4938), ('U05BB23C0302', 4953), ('U05BB23C0303', 4968), ('U05BB23C0304', 4983), ('U05BB23C0305', 4997), ('U05BB23C0306', 5012), ('U05BB23C0307', 5027), ('U05BB23C0308', 5042), ('U05BB23C0309', 5057), ('U05BB23C0310', 5072), ('U05BB23C0311', 5087), ('U05BB23C0312', 5102), ('U05BB23C0313', 5117), ('U05BB23C0314', 5131), ('U05BB23C0315', 5146), ('U05BB23C0316', 5161), ('U05BB23C0317', 5176), ('U05BB23C0318', 5191), ('U05BB23C0319', 5206), ('U05BB23C0320', 5221), ('U05BB23C0321', 5236), ('U05BB23C0322', 5251), ('U05BB23C0323', 5265), ('U05BB23C0324', 5280), ('U05BB23C0325', 5295), ('U05BB23C0326', 5310), ('U05BB23C0327', 5325), ('U05BB23C0329', 5340), ('U05BB23C0331', 5355), ('U05BB23C0332', 5370), ('U05BB23C0333', 5385), ('U05BB23C0334', 5399), ('U05BB23C0335', 5414), ('U05BB23C0336', 5429), ('U05BB23C0337', 5444), ('U05BB23C0338', 5459), ('U05BB23C0339', 5474), ('U05BB23C0340', 5489), ('U05BB23C0341', 5504), ('U05BB23C0342', 5519), ('U05BB23C0343', 5533), ('U05BB23C0344', 5548), ('U05BB23C0345', 5563), ('U05BB23C0346', 5578), ('U05BB23C0347', 5593), ('U05BB23C0348', 5608), ('U05BB23C0349', 5623), ('U05BB23C0350', 5638), ('U05BB23C0351', 5653), ('U05BB23C0353', 5667), ('U05BB23C0354', 5682), ('U05BB23C0355', 5697), ('U05BB23C0356', 5712), ('U05BB23C0357', 5727), ('U05BB23C0358', 5742), ('U05BB23C0359', 5757), ('U05BB23C0360', 5772), ('U05BB23C0361', 5787)]

,Sl. No,Name,USN,BCACAEN302 - R PROGRAMMING,BCMCMCN301 - Corporate Accounting,BCMCMCN302 - Business Statistics,BCMCMCN303 - Cost Accounting,BCMENLN301 - Generic English,BCMHDLN301 - Hindi,BCMKALN302 - Kannada,...,COMNSSN302 - NSS,COMRRSN302 - Rovers and Rangers,COMSRSN302 - Sports II,COMYRSN302 - Youth Red Cross,Result,Total Marks,Max Marks,Percentage,CGPA,SGPA
0,1,ASHRAYA SHETTY,U05BB21C0040,N/A,N/A,N/A,Pass,N/A,N/A,N/A,...,N/A,N/A,N/A,N/A,PASS,46,100,46.00,6.39,5.78
1,2,SHASHANK S,U05BB21C0050,N/A,Fail,N/A,Fail,N/A,N/A,N/A,...,N/A,N/A,N/A,N/A,FAIL,57,200,28.50,NaN,NaN
2,3,NISHA,U05BB21C0100,N/A,N/A,N/A,N/A,N/A,N/A,N/A,...,N/A,N/A,N/A,N/A,PASS,37,50,74.00,7.37,7.14
3,4,PANNAGA V,U05BB21C0116,N/A,Fail,N/A,N/A,N/A,N/A,N/A,...,N/A,N/A,N/A,N/A,FAIL,28,100,28.00,NaN,NaN
4,5,THANUSH KHARVI,U05BB21C0198,N/A,Absent,N/A,N/A,N/A,N/A,N/A,...,N/A,N/A,N/A,N/A,FAIL,0,100,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384,385,SHREYA J HEGDE,U05BB23C0357,Pass,Pass,Pass,Pass,Pass,N/A,N/A,...,N/A,Pass,N/A,N/A,PASS,571,700,81.57,9.07,8.48
385,386,KAVYA,U05BB23C0358,Pass,Pass,Pass,Pass,Pass,N/A,Pass,...,N/A,Pass,N/A,N/A,PASS,654,700,93.43,9.55,9.68
386,387,ABDUL ZAHIR,U05BB23C0359,Fail,Fail,Pass,Fail,Pass,Fail,N/A,...,N/A,N/A,N/A,N/A,FAIL,271,700,38.71,NaN,NaN
387,388,ARYA,U05BB23C0360,Pass,Pass,Pass,Pass,Pass,Pass,N/A,...,N/A,N/A,Pass,N/A,PASS,448,700,64.00,6.61,6.68
388,389,SANKETH,U05BB23C0361,Pass,Pass,Pass,Pass,Pass,N/A,Pass,...,Pass,N/A,N/A,N/A,PASS,511,700,73.00,7.52,7.70